/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_template;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.UUID;

import javax.swing.*;

/** 
 *
 * @author Stavroula Niarchou
 */

public class BookingForm extends javax.swing.JFrame {
    //global array list that holds all the bookings
    public static ArrayList<Booking> reservations = new ArrayList(); 
    
    // maximum capacity of the venue per time slot
    final int maximumCapacity = 50; 
    
      
    /**
     *  for each reservation the method checks if the same date and time slot
        have been booked and then 
        checks if with the new party size we exceed maximum capacity
     * @author Stavroula Niarchou
     * @param date
     * @param time
     * @param partySize
     * @return Boolean availability
     */
    public boolean checkAvailability(Date date, String time, int partySize){   
        int availabilityCount = 0;
        boolean availability = false;
        /*for each booking if the date and time match the requested date/time,
        the number of guests of that booking is added to the availability count
        */
        for (int i=0; i < reservations.size(); i++){
            if (date.equals(reservations.get(i).getDate())
                && time.equals(reservations.get(i).getTime()))               
            {
                availabilityCount += reservations.get(i).getPartySize();
            }
        }
        
        /* check if we exceed maximum capacity if we add the number 
        of the new guests to those that have already booked
        */
        if (partySize + availabilityCount <= maximumCapacity){
            availability = true;
            return availability;
        }
        return availability;
        
    }
    // end of checkAvailability method
    
    
    /**
     * creates new instance of class Booking and adds it to the array list 
       of reservations
     * @author Stavroula Niarchou 
     * @param bookingNumber
     * @param name
     * @param phoneNumber
     * @param date
     * @param time
     * @param partySize 
     */
    public void createNewBooking(
            String bookingNumber, 
            String name,
            String phoneNumber, 
            Date date, 
            String time,
            int partySize
    )
    {
        Booking myBooking = new Booking();
        myBooking.setBookingNumber(bookingNumber);
        myBooking.setName(name);
        myBooking.setPhoneNumber(phoneNumber);
        myBooking.setDate(date);
        myBooking.setTime(time);
        myBooking.setPartySize(partySize);
        reservations.add(myBooking);
    }
    // end of createNewBooking method
    
    
    /**
     * tries to parse the string phone number as long to check if it is numeric
     * @author Stavroula Niarchou 
     * @param myNumber
     * @return Boolean validNumber
     */
    public boolean isNumeric(String myNumber){
        boolean validNumber = false;
        try{
            long phoneNumber = Long.parseLong(myNumber);
            validNumber = true;
            return validNumber;
        }
        catch(Exception e){     
        }
        return validNumber;
    }
    // end of isNumeric method
    
    /**
     * receives the full date and sets hours, minutes and seconds to 0
     * @author Stavroula Niarchou
     * @param date
     * @return date (with time set to 0)
     */
    public static Date formatDate(Date date) {
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        return cal.getTime();
    }
    // end of removeTime method
    
    /**
     * Creates new form BookingForm
     */
    
    public BookingForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSlots = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnBook = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblMyBooking = new javax.swing.JLabel();
        SpinnerPartySize = new javax.swing.JSpinner();
        lblPartySize = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        rdoBtnSlot1 = new javax.swing.JRadioButton();
        rdoBtnSlot2 = new javax.swing.JRadioButton();
        rdoBtnSlot3 = new javax.swing.JRadioButton();
        rdoBtnSlot4 = new javax.swing.JRadioButton();
        lblNameError = new javax.swing.JLabel();
        lblPhoneError = new javax.swing.JLabel();
        btnBackToMain = new javax.swing.JButton();
        jCalendar2 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        btnBook.setBackground(new java.awt.Color(0, 0, 51));
        btnBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.setText("Confirm Booking");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Name");

        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhoneNumber.setText("Phone Number");

        lblMyBooking.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMyBooking.setText("MY BOOKING");

        SpinnerPartySize.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));
        SpinnerPartySize.setEditor(new javax.swing.JSpinner.NumberEditor(SpinnerPartySize, ""));

        lblPartySize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPartySize.setText("Guests");

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDate.setText("Date");

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTime.setText("Time");

        btnGroupSlots.add(rdoBtnSlot1);
        rdoBtnSlot1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoBtnSlot1.setSelected(true);
        rdoBtnSlot1.setText("15:00-17:00");

        btnGroupSlots.add(rdoBtnSlot2);
        rdoBtnSlot2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoBtnSlot2.setText("17:00-19:00");

        btnGroupSlots.add(rdoBtnSlot3);
        rdoBtnSlot3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoBtnSlot3.setText("19:00-21:00");

        btnGroupSlots.add(rdoBtnSlot4);
        rdoBtnSlot4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoBtnSlot4.setText("21:00-23:00");

        btnBackToMain.setBackground(new java.awt.Color(0, 0, 51));
        btnBackToMain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToMain.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToMain.setText("Back");
        btnBackToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdoBtnSlot1)
                        .addGap(18, 18, 18)
                        .addComponent(rdoBtnSlot2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPartySize, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SpinnerPartySize, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdoBtnSlot3)
                        .addGap(18, 18, 18)
                        .addComponent(rdoBtnSlot4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBackToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(597, 597, 597)
                                .addComponent(lblPhoneError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(155, 155, 155)
                                .addComponent(lblNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(141, 141, 141)
                                        .addComponent(lblMyBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnBook)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(299, 299, 299))
                                                .addComponent(jCalendar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblMyBooking)
                .addGap(37, 37, 37)
                .addComponent(lblTime)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNameError)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdoBtnSlot1)
                                    .addComponent(rdoBtnSlot2))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdoBtnSlot3)
                                    .addComponent(rdoBtnSlot4))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPartySize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SpinnerPartySize, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPhoneNumber)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBackToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoneError)
                            .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When the button is clicked it gets user input from the jFrame and 
     * calls the checkAvailability and createNewBooking methods
     * @author Stavroula Niarchou
     * @param evt 
     */
    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // create a random booking number
        UUID BookingNumber = UUID.randomUUID();
        
       // get user input for date and set time element to 0
        Date myDate = jCalendar2.getDate();
        Date date = formatDate(myDate);
        
        // get user input for time, partySize, name , phone number
        String time;
        if (rdoBtnSlot1.isSelected()){
            time = "15:00-17:00";
        }
        else if (rdoBtnSlot2.isSelected()){
            time = "17:00-19:00";
        }
        else if (rdoBtnSlot3.isSelected()){
            time = "19:00-21:00";
        }
        else{
            time = "21:00-23:00";
        }
        
       int partySize = (Integer)SpinnerPartySize.getValue();
  
       String name = txtName.getText();
       
       String phoneNumber = txtPhoneNumber.getText();
       
       /*check if phone number is valid
       if it's not valid a message is displayed, 
       otherwise the program continues to execute
       */
       boolean valid = isNumeric(phoneNumber);
       if (valid == false){
          JOptionPane.showMessageDialog
            (null,
             "Please enter a valid phone number",
             "Invalid number", 
             JOptionPane.INFORMATION_MESSAGE); 
       }
       else{
        /* check availability and call the createNewBooking
           method if there is availability
        */
        boolean availability = checkAvailability(date, time, partySize);
        if (availability == true){
            createNewBooking(
                BookingNumber.toString(), 
                name, 
                phoneNumber, 
                date, 
                time, 
                partySize
            );
            JOptionPane.showMessageDialog(
               null, "Your booking reference is " + 
                BookingNumber.toString(), 
               "Booking Successful!", 
               JOptionPane.INFORMATION_MESSAGE
            );
        }
        else{
            JOptionPane.showMessageDialog(
                null, 
                """
                    We are sorry but we are fully booked on this date and time
                    Please choose a different date or time slot""", 
               "Booking unsuccessful", 
               JOptionPane.INFORMATION_MESSAGE);
        }
        
        txtName.setText("");
        txtPhoneNumber.setText("");
        rdoBtnSlot1.setSelected(true);
        SpinnerPartySize.setValue(1);
        
       }
      
    }//GEN-LAST:event_btnBookActionPerformed
    /**
     * Button takes user back to the main form 
     * @author Stavroula Niarchou
     * @param evt 
     */
    private void btnBackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMainActionPerformed
       MainForm main = new MainForm();
       main.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnBackToMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingForm().setVisible(true);
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerPartySize;
    private javax.swing.JButton btnBackToMain;
    private javax.swing.JButton btnBook;
    private javax.swing.ButtonGroup btnGroupSlots;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMyBooking;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblPartySize;
    private javax.swing.JLabel lblPhoneError;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblTime;
    private javax.swing.JRadioButton rdoBtnSlot1;
    private javax.swing.JRadioButton rdoBtnSlot2;
    private javax.swing.JRadioButton rdoBtnSlot3;
    private javax.swing.JRadioButton rdoBtnSlot4;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
