package oop_template;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultListModel;

/**
 *
 * @author parker
 */
public class MenuView extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelViewMenu = new javax.swing.JPanel();
        lblViewMenu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMenuList1 = new javax.swing.JList<>();
        jViewMenuFiles1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelViewMenu.setBackground(new java.awt.Color(255, 255, 0));

        lblViewMenu.setBackground(new java.awt.Color(0, 0, 51));
        lblViewMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblViewMenu.setForeground(new java.awt.Color(0, 0, 0));
        lblViewMenu.setText("View Menu");

        jMenuList1.setBackground(new java.awt.Color(0, 0, 51));
        jMenuList1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jMenuList1);

        jViewMenuFiles1.setBackground(new java.awt.Color(0, 0, 51));
        jViewMenuFiles1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jViewMenuFiles1.setForeground(new java.awt.Color(255, 255, 255));
        jViewMenuFiles1.setText("View Files");
        jViewMenuFiles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewMenuFiles1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(0, 0, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanelViewMenuLayout = new javax.swing.GroupLayout(jPanelViewMenu);
        jPanelViewMenu.setLayout(jPanelViewMenuLayout);
        jPanelViewMenuLayout.setHorizontalGroup(
            jPanelViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewMenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblViewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelViewMenuLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jViewMenuFiles1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanelViewMenuLayout.setVerticalGroup(
            jPanelViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblViewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelViewMenuLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jViewMenuFiles1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelViewMenuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelViewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelViewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * reads data from selected text file into the text area
     */
    public void showFiles() {
                
        // removes all text from the text area
        // and then creates variable for the selected file
        jTextArea1.removeAll();
        String filename = jMenuList1.getSelectedValue();
        
        // reads the file line by line to the text area
        File file = new File("MenuFileStorage/" + filename);
        try(BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            while((line = reader.readLine()) != null) {
                System.out.println(line);
                jTextArea1.read(reader, null);
            }
            
        }
        catch (IOException e) {
            e.printStackTrace();
            System.out.print("Error reading file");
        }
    }
    
    
    /**
     * executes showFiles method
     * @param evt 
     */
    private void jMenuList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuList1MouseClicked
       showFiles();
    }//GEN-LAST:event_jMenuList1MouseClicked

    
    /**
     * user selects show files button, files in MenuFileStorage 
     * folder appear in the jList
     * @param evt 
     */
    private void jViewMenuFiles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewMenuFiles1ActionPerformed

        DefaultListModel model = new DefaultListModel();
        File path = new File("MenuFileStorage");
        
        // uses the menuFileStorage folder to 
        // get text files created by user and adds them
        // to the jList
        File[] filelist = path.listFiles();
        for(File f : filelist) {
            model.addElement(f.getName());
        }
        jMenuList1.setModel(model);
    }//GEN-LAST:event_jViewMenuFiles1ActionPerformed

    
    /**
     * goes back to main menu
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainForm main = new MainForm();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jMenuList1;
    private javax.swing.JPanel jPanelViewMenu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jViewMenuFiles1;
    private javax.swing.JLabel lblViewMenu;
    // End of variables declaration//GEN-END:variables
}
