/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_template;

import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 *
 * @author 50029212
 */
public class StaffOptions extends javax.swing.JFrame {

    /**
     * Creates new form StaffOptions
     */
    public StaffOptions() {
        initComponents();
    }

    /**
     * checks if menuFileStorage exits and creates it if not
     * @author parker johnson
     */
    public void menuFileCheck() {
        
        File file = new File("H:\\s2023\\Object Oriented Programming\\nice\\oop-group-project-parker_zara_lina_john_group_2\\MenuFileStorage");
        
        
        if(file.exists()) {
            System.out.print("file exists");
        } else {
            file.mkdir();
            file.isDirectory();
            file.isFile();
            System.out.print("file doesnt exist and was created");
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelViewMenu = new javax.swing.JPanel();
        btnEditReservations = new javax.swing.JButton();
        btnEdiutMenu = new javax.swing.JButton();
        btnEditStaff = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));

        jPanelViewMenu.setBackground(new java.awt.Color(255, 255, 0));

        btnEditReservations.setBackground(new java.awt.Color(0, 0, 51));
        btnEditReservations.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditReservations.setForeground(new java.awt.Color(255, 255, 255));
        btnEditReservations.setText("Edit Reservations");
        btnEditReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditReservationsActionPerformed(evt);
            }
        });

        btnEdiutMenu.setBackground(new java.awt.Color(0, 0, 51));
        btnEdiutMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdiutMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnEdiutMenu.setText("Edit Menu");
        btnEdiutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdiutMenuActionPerformed(evt);
            }
        });

        btnEditStaff.setBackground(new java.awt.Color(0, 0, 51));
        btnEditStaff.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnEditStaff.setText("Edit Staff");
        btnEditStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStaffActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelViewMenuLayout = new javax.swing.GroupLayout(jPanelViewMenu);
        jPanelViewMenu.setLayout(jPanelViewMenuLayout);
        jPanelViewMenuLayout.setHorizontalGroup(
            jPanelViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewMenuLayout.createSequentialGroup()
                .addGroup(jPanelViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelViewMenuLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jPanelViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdiutMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelViewMenuLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanelViewMenuLayout.setVerticalGroup(
            jPanelViewMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewMenuLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnEditReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdiutMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelViewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelViewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * opens the edit reservations form
     * @param evt 
     */
    private void btnEditReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditReservationsActionPerformed
        UpdateDeleteBooking updel = new UpdateDeleteBooking();
        updel.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditReservationsActionPerformed

    /**
     * closes staff options form and opens the main form
     * @param evt 
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainForm main = new MainForm();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * execute menuFileCheck method
     * opens the menuOptions form
     * @param evt 
     */
    private void btnEdiutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdiutMenuActionPerformed
        menuFileCheck();
        MenuOptionsJ menu = new MenuOptionsJ();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEdiutMenuActionPerformed

    private void btnEditStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStaffActionPerformed
        StaffFrame staff = new StaffFrame();
        staff.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEditReservations;
    private javax.swing.JButton btnEditStaff;
    private javax.swing.JButton btnEdiutMenu;
    private javax.swing.JPanel jPanelViewMenu;
    // End of variables declaration//GEN-END:variables
}
